"""Base strategy class for trading strategies.

This is a paper-trading demo - strategies should be safe
and well-tested before any consideration of live use.
"""
from abc import ABC, abstractmethod
from dataclasses import dataclass
from decimal import Decimal


@dataclass
class Signal:
    """Trading signal generated by a strategy."""
    symbol: str
    action: str  # 'buy', 'sell', 'hold'
    confidence: float  # 0.0 to 1.0
    quantity: Decimal | None = None
    reason: str = ""


class BaseStrategy(ABC):
    """Base class for trading strategies.

    All strategies must implement the generate_signals method.
    This is a paper-trading demo - strategies should be safe
    and well-tested before any consideration of live use.
    """

    @abstractmethod
    def generate_signals(self) -> list[Signal]:
        """Generate trading signals based on strategy logic.

        Returns:
            List of Signal objects representing desired actions
        """
        pass
